# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\traffic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Desing(object):
    def setupUi(self, Desing):
        Desing.setObjectName("Desing")
        Desing.resize(947, 743)
        self.treeWidget = QtWidgets.QTreeWidget(Desing)
        self.treeWidget.setGeometry(QtCore.QRect(20, 170, 501, 561))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.treeWidget.setFont(font)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(225)
        self.RED = QtWidgets.QLabel(Desing)
        self.RED.setGeometry(QtCore.QRect(40, 40, 91, 91))
        self.RED.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                               "border-radius: 45px;\n"
                               "min-height: 10px;\n"
                               "min-width: 10px;")
        self.RED.setObjectName("RED")
        self.YELLOW = QtWidgets.QLabel(Desing)
        self.YELLOW.setGeometry(QtCore.QRect(160, 40, 91, 91))
        self.YELLOW.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                  "border-radius: 45px;\n"
                                  "min-height: 10px;\n"
                                  "min-width: 10px;")
        self.YELLOW.setObjectName("YELLOW")
        self.LEFT = QtWidgets.QLabel(Desing)
        self.LEFT.setGeometry(QtCore.QRect(280, 40, 91, 91))
        self.LEFT.setSizeIncrement(QtCore.QSize(0, 0))
        self.LEFT.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(100)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.LEFT.setFont(font)
        self.LEFT.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                "color: rgb(0, 0, 0);\n"
                                "border-radius: 45px;\n"
                                "min-height: 10px;\n"
                                "min-width: 10px;")
        self.LEFT.setAlignment(QtCore.Qt.AlignCenter)
        self.LEFT.setObjectName("LEFT")
        self.GREEN = QtWidgets.QLabel(Desing)
        self.GREEN.setGeometry(QtCore.QRect(400, 40, 91, 91))
        self.GREEN.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                 "border-radius: 45px;\n"
                                 "min-height: 10px;\n"
                                 "min-width: 10px;")
        self.GREEN.setObjectName("GREEN")
        self.label = QtWidgets.QLabel(Desing)
        self.label.setGeometry(QtCore.QRect(20, 20, 501, 131))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Desing)
        self.pushButton.setGeometry(QtCore.QRect(550, 650, 161, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Desing)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 650, 161, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.treeView = QtWidgets.QTreeView(Desing)
        self.treeView.setGeometry(QtCore.QRect(530, 20, 401, 621))
        self.treeView.setObjectName("treeView")
        self.label.raise_()
        self.treeWidget.raise_()
        self.RED.raise_()
        self.YELLOW.raise_()
        self.LEFT.raise_()
        self.GREEN.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.treeView.raise_()

        self.retranslateUi(Desing)
        QtCore.QMetaObject.connectSlotsByName(Desing)


    def retranslateUi(self, Desing):
        _translate = QtCore.QCoreApplication.translate
        Desing.setWindowTitle(_translate("Desing", "WizardPage"))
        self.treeWidget.headerItem().setText(0, _translate("Desing", "TIME"))
        self.treeWidget.headerItem().setText(1, _translate("Desing", "LED"))

        self.RED.setText(_translate("Desing", "<html><head/><body><p><br/></p></body></html>"))
        self.YELLOW.setText(_translate("Desing", "<html><head/><body><p><br/></p></body></html>"))
        self.LEFT.setText(_translate("Desing",
                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "</style></head><body style=\" font-family:\'Arial\'; font-size:100pt; font-weight:400; font-style:normal;\">\n"
                                     "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600;\">←</span></p></body></html>"))
        self.GREEN.setText(_translate("Desing", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("Desing", "삭제"))
        self.pushButton_2.setText(_translate("Desing", "저장"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Desing = QtWidgets.QWizardPage()
    ui = Ui_Desing()
    ui.setupUi(Desing)
    Desing.show()
    sys.exit(app.exec_())
